/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

 class App {
    public static void main(String[] args) {
        //String filePath = "/Users/neerajreddy/Desktop/student.csv"; // Make sure this file exists in your project directory
        String resourceName = "student.csv";

        try (InputStream inputStream = App.class.getClassLoader().getResourceAsStream(resourceName);
             BufferedReader br = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8))) { // Specify encoding for safety

            if (inputStream == null) {
                System.err.println("Error: Resource '" + resourceName + "' not found in the classpath!");
                System.err.println("Please ensure '" + resourceName + "' is placed in 'src/main/resources'.");
                return; // Exit if the resource isn't found
            }

            String line;
            boolean header = true;

            while ((line = br.readLine()) != null) {
                // Skip header row
                if (header) {
                    header = false;
                    continue;
                }


                // Split the line by comma
                String[] values = line.split(",");

                
                int age = Integer.parseInt(values[2]);
                int marks = Integer.parseInt(values[3]);
                if (age == 15 && marks > 50) {
                    System.out.println("Matched Student:");
                    System.out.println("ID: " + values[0] + ", Name: " + values[1] +
                                       ", Age: " + values[2] + ", Marks: " + values[3]);
                }
            }

        
        } catch (IOException e) {
            System.out.println("Error reading the file!");
        
        }
    }
}
