/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

// public class App{
//     public int twoMul(int a, int b)
//     {
//         return a*b;
//     }

//     public static void main(String[] args) {
//         App obj = new App();
//         int Mul= obj.twoMul(8, 10);
//         System.out.println(Mul);
//     }
// }

// public class App{
//     public static void main(String[] args) {
//         String sentence = " fox jumps over the lazy fox";
//         String [] words = sentence.toLowerCase().split(" ");
//         int maxcount = 0;
//         String mostfrequent ="";
//         for(int i = 0;i< words.length;i++)
//         {
//             int count = 1;
//             for(int j = i+1;j< words.length;j++)
//             {//int count = 1;
//                 if (words[i].equals(words[j])) {
//                     count++;
                    
//                 }
//             }
//             if (count > maxcount) {
//                 mostfrequent = words[i];
//                 maxcount = count;
                
//             }
//         }
//         System.out.println("The most frequent word is : " +mostfrequent+ ", it got repeated "+maxcount+ " times.");
        


//     }

// }



import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

 class App {
    public static void main(String[] args) {
        //String filePath = "/Users/neerajreddy/Desktop/student.csv"; // Make sure this file exists in your project directory
        String resourceName = "student.csv";

        try (InputStream inputStream = App.class.getClassLoader().getResourceAsStream(resourceName);
             BufferedReader br = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8))) { // Specify encoding for safety

            if (inputStream == null) {
                System.err.println("Error: Resource '" + resourceName + "' not found in the classpath!");
                System.err.println("Please ensure '" + resourceName + "' is placed in 'src/main/resources'.");
                return; // Exit if the resource isn't found
            }

            String line;
            boolean header = true;

            while ((line = br.readLine()) != null) {
                // Skip header row
                if (header) {
                    header = false;
                    continue;
                }


                // Split the line by comma
                String[] values = line.split(",");

                
                int age = Integer.parseInt(values[2]);
                int marks = Integer.parseInt(values[3]);
                if (age == 15 && marks > 50) {
                    System.out.println("Matched Student:");
                    System.out.println("ID: " + values[0] + ", Name: " + values[1] +
                                       ", Age: " + values[2] + ", Marks: " + values[3]);
                }
            }

        
        } catch (IOException e) {
            System.out.println("Error reading the file!");
        
        }
    }
}